title: "Samuel Freitas"
description: "Software Developer & QA Automation"
url: "https://samfreitasxs.github.io" # Adicione o https://
baseurl: ""

# Configurações do Tema
remote_theme: "mmistakes/so-simple-theme"
locale: "pt-BR"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

author:
  name: "Samuel Freitas"
  # CORREÇÃO: O nome no seu VS Code é .png, não .jpg
  avatar: "/assets/images/bio-foto.png" 
  bio: "Desenvolvedor focado em automação e qualidade de software."
  location: "Maringá, PR"
  links:
    - title: "GitHub"
      url: "https://github.com/samfreitasxs"
      icon: "fab fa-fw fa-github"
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/samuelfreitass/"
      icon: "fab fa-fw fa-linkedin"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      classes: "wide"
      author_profile: true